services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: grafana_db
      POSTGRES_USER: grafana
      POSTGRES_PASSWORD: let-grafana-in-please
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "5432:5432"
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
        interval: 10s
        timeout: 5s
        retries: 5

  grafana:
    image: grafana/grafana:11.6.2-ubuntu
    container_name: grafana_11.6.2
    ports:
        - 3000:3000
    volumes:
        - ./dashboards:/var/lib/grafana/dashboards
        - ./provisioning:/etc/grafana/provisioning
    environment:
        - GF_INSTALL_PLUGINS=volkovlabs-form-panel,volkovlabs-echarts-panel,volkovlabs-image-panel,marcusolsson-static-datasource
    depends_on:
        db:
            condition: service_healthy