services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
        - "5432:5432"
    # networks:
    #     - grafana_network
    healthcheck:
        test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
        interval: 10s
        timeout: 5s
        retries: 5

  grafana:
    image: grafana/grafana:11.6.2-ubuntu
    container_name: grafana_11.6.2
    ports:
        - 3000:3000
    # networks:
    #     - grafana_network
    volumes:
        - ./dashboards:/var/lib/grafana/dashboards
        - ./provisioning:/etc/grafana/provisioning
        # - grafana_data:/var/lib/grafana
    environment:
        - GF_INSTALL_PLUGINS=volkovlabs-form-panel,volkovlabs-echarts-panel,volkovlabs-image-panel,marcusolsson-static-datasource
    depends_on:
        db:
            condition: service_healthy

# networks:
#   grafana_network:
#     driver: bridge

# volumes:
#   grafana_data:
#     driver: local